### ISSUE TITLE
Prysm docker images

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum2-docker-build#1]
Build a secure docker image for prysm:

- beacon-chain
- validator
- slasher

Docker image features:
- Using non-priviledged user
- Apparmor or similar
- No package managers
- Automized and triggered builds

This replaces https://github.com/stefa2k/ethereum2-docker-compose/issues/19

**Comment by sapien99** [comment]
https://github.com/stereum-dev/ethereum2-docker-build/tree/main/prysm, arm build in dedicted issue
