### ISSUE TITLE
Remove SSH/curl/wget

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum2-docker-build#5]
important is to remove ssh/curl/wget commands, because you could still download binarys and execute them

**Comment by sapien99** [comment]
Base image is clean, will check also the other ones. 

`docker run -it --entrypoint sh stereum/beacon-base:buster
# wget
sh: 1: wget: not found
# curl
sh: 2: curl: not found
# ssh
sh: 3: ssh: not found`

But of course You always of course have the possibility to add an executable via docker cp from outside :-(

**Comment by sapien99** [comment]
other images also without those 3. Guess we can close this one
